spring:
  application:
    name: marcaciones-service
  profiles:
    # Para desarrollo local: -Dspring.profiles.active=local
    # Para producción: -Dspring.profiles.active=prod
    active: ${SPRING_PROFILES_ACTIVE:local}