# Configuración adicional para perfil DEV
# La BD principal viene del Config Server
# GDR usa la MISMA BD (configurado en GdrDBConfig.java con @Profile)

spring:
  config:
    import: configserver:${CONFIG_SERVER_URL}
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}

# URL de la Plataforma Integral (PIGRH)
plataforma-integral:
  url: ${PIGRH_URL:https://pigrh.essalud.gob.pe/verificar-sso}
